// // <auto-generated>
// //     Generated by the protocol buffer compiler.  DO NOT EDIT!
// //     source: msg.proto
// // </auto-generated>
// #pragma warning disable 1591, 0612, 3021
// #region Designer generated code

// using pb = global::Google.Protobuf;
// using pbc = global::Google.Protobuf.Collections;
// using pbr = global::Google.Protobuf.Reflection;
// using scg = global::System.Collections.Generic;
// namespace Msg {

//   /// <summary>Holder for reflection information generated from msg.proto</summary>
//   public static partial class MsgReflection {

//     #region Descriptor
//     /// <summary>File descriptor for msg.proto</summary>
//     public static pbr::FileDescriptor Descriptor {
//       get { return descriptor; }
//     }
//     private static pbr::FileDescriptor descriptor;

//     static MsgReflection() {
//       byte[] descriptorData = global::System.Convert.FromBase64String(
//           string.Concat(
//             "Cgltc2cucHJvdG8SA21zZyIVCgVIZWxsbxIMCgRkYXRhGAEgASgJIi4KCExv",
//             "Z2luTXNnEhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIhkK",
//             "CUxvZ2luUmVzcBIMCgRjb2RlGAEgASgFYgZwcm90bzM="));
//       descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//           new pbr::FileDescriptor[] { },
//           new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
//             new pbr::GeneratedClrTypeInfo(typeof(global::Msg.Hello), global::Msg.Hello.Parser, new[]{ "Data" }, null, null, null, null),
//             new pbr::GeneratedClrTypeInfo(typeof(global::Msg.LoginMsg), global::Msg.LoginMsg.Parser, new[]{ "Username", "Password" }, null, null, null, null),
//             new pbr::GeneratedClrTypeInfo(typeof(global::Msg.LoginResp), global::Msg.LoginResp.Parser, new[]{ "Code" }, null, null, null, null)
//           }));
//     }
//     #endregion

//   }
//   #region Messages
//   public sealed partial class Hello : pb::IMessage<Hello> {
//     private static readonly pb::MessageParser<Hello> _parser = new pb::MessageParser<Hello>(() => new Hello());
//     private pb::UnknownFieldSet _unknownFields;
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pb::MessageParser<Hello> Parser { get { return _parser; } }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pbr::MessageDescriptor Descriptor {
//       get { return global::Msg.MsgReflection.Descriptor.MessageTypes[0]; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     pbr::MessageDescriptor pb::IMessage.Descriptor {
//       get { return Descriptor; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public Hello() {
//       OnConstruction();
//     }

//     partial void OnConstruction();

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public Hello(Hello other) : this() {
//       data_ = other.data_;
//       _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public Hello Clone() {
//       return new Hello(this);
//     }

//     /// <summary>Field number for the "data" field.</summary>
//     public const int DataFieldNumber = 1;
//     private string data_ = "";
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public string Data {
//       get { return data_; }
//       set {
//         data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override bool Equals(object other) {
//       return Equals(other as Hello);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public bool Equals(Hello other) {
//       if (ReferenceEquals(other, null)) {
//         return false;
//       }
//       if (ReferenceEquals(other, this)) {
//         return true;
//       }
//       if (Data != other.Data) return false;
//       return Equals(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override int GetHashCode() {
//       int hash = 1;
//       if (Data.Length != 0) hash ^= Data.GetHashCode();
//       if (_unknownFields != null) {
//         hash ^= _unknownFields.GetHashCode();
//       }
//       return hash;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override string ToString() {
//       return pb::JsonFormatter.ToDiagnosticString(this);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void WriteTo(pb::CodedOutputStream output) {
//       if (Data.Length != 0) {
//         output.WriteRawTag(10);
//         output.WriteString(Data);
//       }
//       if (_unknownFields != null) {
//         _unknownFields.WriteTo(output);
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public int CalculateSize() {
//       int size = 0;
//       if (Data.Length != 0) {
//         size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
//       }
//       if (_unknownFields != null) {
//         size += _unknownFields.CalculateSize();
//       }
//       return size;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(Hello other) {
//       if (other == null) {
//         return;
//       }
//       if (other.Data.Length != 0) {
//         Data = other.Data;
//       }
//       _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(pb::CodedInputStream input) {
//       uint tag;
//       while ((tag = input.ReadTag()) != 0) {
//         switch(tag) {
//           default:
//             _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//             break;
//           case 10: {
//             Data = input.ReadString();
//             break;
//           }
//         }
//       }
//     }

//   }

//   public sealed partial class LoginMsg : pb::IMessage<LoginMsg> {
//     private static readonly pb::MessageParser<LoginMsg> _parser = new pb::MessageParser<LoginMsg>(() => new LoginMsg());
//     private pb::UnknownFieldSet _unknownFields;
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pb::MessageParser<LoginMsg> Parser { get { return _parser; } }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pbr::MessageDescriptor Descriptor {
//       get { return global::Msg.MsgReflection.Descriptor.MessageTypes[1]; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     pbr::MessageDescriptor pb::IMessage.Descriptor {
//       get { return Descriptor; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginMsg() {
//       OnConstruction();
//     }

//     partial void OnConstruction();

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginMsg(LoginMsg other) : this() {
//       username_ = other.username_;
//       password_ = other.password_;
//       _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginMsg Clone() {
//       return new LoginMsg(this);
//     }

//     /// <summary>Field number for the "username" field.</summary>
//     public const int UsernameFieldNumber = 1;
//     private string username_ = "";
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public string Username {
//       get { return username_; }
//       set {
//         username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//       }
//     }

//     /// <summary>Field number for the "password" field.</summary>
//     public const int PasswordFieldNumber = 2;
//     private string password_ = "";
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public string Password {
//       get { return password_; }
//       set {
//         password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override bool Equals(object other) {
//       return Equals(other as LoginMsg);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public bool Equals(LoginMsg other) {
//       if (ReferenceEquals(other, null)) {
//         return false;
//       }
//       if (ReferenceEquals(other, this)) {
//         return true;
//       }
//       if (Username != other.Username) return false;
//       if (Password != other.Password) return false;
//       return Equals(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override int GetHashCode() {
//       int hash = 1;
//       if (Username.Length != 0) hash ^= Username.GetHashCode();
//       if (Password.Length != 0) hash ^= Password.GetHashCode();
//       if (_unknownFields != null) {
//         hash ^= _unknownFields.GetHashCode();
//       }
//       return hash;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override string ToString() {
//       return pb::JsonFormatter.ToDiagnosticString(this);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void WriteTo(pb::CodedOutputStream output) {
//       if (Username.Length != 0) {
//         output.WriteRawTag(10);
//         output.WriteString(Username);
//       }
//       if (Password.Length != 0) {
//         output.WriteRawTag(18);
//         output.WriteString(Password);
//       }
//       if (_unknownFields != null) {
//         _unknownFields.WriteTo(output);
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public int CalculateSize() {
//       int size = 0;
//       if (Username.Length != 0) {
//         size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
//       }
//       if (Password.Length != 0) {
//         size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
//       }
//       if (_unknownFields != null) {
//         size += _unknownFields.CalculateSize();
//       }
//       return size;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(LoginMsg other) {
//       if (other == null) {
//         return;
//       }
//       if (other.Username.Length != 0) {
//         Username = other.Username;
//       }
//       if (other.Password.Length != 0) {
//         Password = other.Password;
//       }
//       _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(pb::CodedInputStream input) {
//       uint tag;
//       while ((tag = input.ReadTag()) != 0) {
//         switch(tag) {
//           default:
//             _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//             break;
//           case 10: {
//             Username = input.ReadString();
//             break;
//           }
//           case 18: {
//             Password = input.ReadString();
//             break;
//           }
//         }
//       }
//     }

//   }

//   public sealed partial class LoginResp : pb::IMessage<LoginResp> {
//     private static readonly pb::MessageParser<LoginResp> _parser = new pb::MessageParser<LoginResp>(() => new LoginResp());
//     private pb::UnknownFieldSet _unknownFields;
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pb::MessageParser<LoginResp> Parser { get { return _parser; } }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public static pbr::MessageDescriptor Descriptor {
//       get { return global::Msg.MsgReflection.Descriptor.MessageTypes[2]; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     pbr::MessageDescriptor pb::IMessage.Descriptor {
//       get { return Descriptor; }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginResp() {
//       OnConstruction();
//     }

//     partial void OnConstruction();

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginResp(LoginResp other) : this() {
//       code_ = other.code_;
//       _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public LoginResp Clone() {
//       return new LoginResp(this);
//     }

//     /// <summary>Field number for the "code" field.</summary>
//     public const int CodeFieldNumber = 1;
//     private int code_;
//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public int Code {
//       get { return code_; }
//       set {
//         code_ = value;
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override bool Equals(object other) {
//       return Equals(other as LoginResp);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public bool Equals(LoginResp other) {
//       if (ReferenceEquals(other, null)) {
//         return false;
//       }
//       if (ReferenceEquals(other, this)) {
//         return true;
//       }
//       if (Code != other.Code) return false;
//       return Equals(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override int GetHashCode() {
//       int hash = 1;
//       if (Code != 0) hash ^= Code.GetHashCode();
//       if (_unknownFields != null) {
//         hash ^= _unknownFields.GetHashCode();
//       }
//       return hash;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public override string ToString() {
//       return pb::JsonFormatter.ToDiagnosticString(this);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void WriteTo(pb::CodedOutputStream output) {
//       if (Code != 0) {
//         output.WriteRawTag(8);
//         output.WriteInt32(Code);
//       }
//       if (_unknownFields != null) {
//         _unknownFields.WriteTo(output);
//       }
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public int CalculateSize() {
//       int size = 0;
//       if (Code != 0) {
//         size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
//       }
//       if (_unknownFields != null) {
//         size += _unknownFields.CalculateSize();
//       }
//       return size;
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(LoginResp other) {
//       if (other == null) {
//         return;
//       }
//       if (other.Code != 0) {
//         Code = other.Code;
//       }
//       _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//     }

//     [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//     public void MergeFrom(pb::CodedInputStream input) {
//       uint tag;
//       while ((tag = input.ReadTag()) != 0) {
//         switch(tag) {
//           default:
//             _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//             break;
//           case 8: {
//             Code = input.ReadInt32();
//             break;
//           }
//         }
//       }
//     }

//   }

//   #endregion

// }

// #endregion Designer generated code
